const test=require('node:test'),assert=require('node:assert/strict');
const {Controller}=require('../minigame/js/controller'),{Platform}=require('../minigame/js/platform'),{Game,available}=require('../minigame/js/core'),{beijingDate,seedFor,applyReward,clone}=require('../minigame/js/daily'),{AdGateway}=require('../minigame/js/ads');
function setup({store={},level,version='develop',time='2026-09-30T15:59:00Z'}={}){let now=Date.parse(time);const api={getAccountInfoSync:()=>({miniProgram:{envVersion:version}}),getLaunchOptionsSync:()=>({query:level?{level}:{}}),getStorageSync:k=>store[k],setStorageSync:(k,v)=>store[k]=clone(v)};const p=new Platform(api),c=new Controller(p,()=>now);return {c,p,store,setTime:t=>now=Date.parse(t),reload:()=>new Controller(p,()=>now)};}
function win(c){for(const id of c.game.solution)if(c.game.tiles[id].zone==='board')assert.equal(c.pick(id),true);assert.equal(c.game.status,'won');}
test('TEST-DAILY-13 interrupted commit cannot reload earlier tools/board',()=>{const t=setup({level:20}),c=t.c,write=t.p.api.setStorageSync;t.p.api.setStorageSync=(k,v)=>{if(k.endsWith('daily.v2'))throw Error('disk full');write(k,v);};assert.equal(c.pick(c.game.solution[0]),true);assert.equal(c.modal,'saveError');assert.equal(t.reload().modal,'storage');t.p.api.setStorageSync=write;c.action('retrySave');assert.equal(c.modal,null);const r=t.reload();r.action('resume');assert.deepEqual(r.game.serialize(),c.game.serialize());});
test('TEST-DAILY-14 foreground return requires explicit resume without refilling tools',()=>{const {c}=setup();c.pick(c.game.solution[0]);c.tool('undo');const before=c.game.serialize();c.offerResume();assert.equal(c.modal,'resume');assert.equal(c.tool('shuffle'),false);c.action('resume');assert.deepEqual(c.game.serialize(),before);});
function full(g){g.tray=[];g.tiles.forEach((t,i)=>{t.zone=i<7?'tray':'board';if(i<7)g.tray.push(i);});g.history=null;g.settle();}
test('TEST-DAILY-01 Beijing midnight and fixed daily boards, provisional 90 boards solve',()=>{assert.equal(beijingDate(Date.parse('2026-09-30T15:59:59Z')),'2026-09-30');assert.equal(beijingDate(Date.parse('2026-09-30T16:00:00Z')),'2026-10-01');for(const date of ['2026-09-30','2026-10-01','2026-10-02'])for(let n=1;n<=30;n++){const g=new Game(n,seedFor(date,n)),copy=new Game(n,seedFor(date,n));assert.deepEqual(g.tiles,copy.tiles);for(const id of g.solution)assert.equal(g.pick(id),true);assert.equal(g.status,'won');}assert.notDeepEqual(new Game(20,seedFor('2026-09-30',20)).tiles,new Game(20,seedFor('2026-10-01',20)).tiles);});
test('TEST-DAILY-02 tools shared across levels, undo not refunded, new run replenishes',()=>{const {c}=setup();c.pick(c.game.solution[0]);c.tool('undo');win(c);c.action('next');assert.equal(c.game.tools.undo,0);assert.equal(c.game.tools.shuffle,1);c.start(1);assert.deepEqual(c.game.tools,{undo:1,shuffle:1,remove:1});assert.ok(c.saved.completed.includes(1));assert.equal(c.saved.history.at(-1).result,'abandoned');});
test('TEST-DAILY-03 exact resume includes reserve order, undo and random state',()=>{const t=setup({level:20}),c=t.c;for(const id of c.game.solution.slice(0,3))c.pick(id);c.tool('remove');c.pick(c.game.reserve[1].id);const before=c.game.serialize(),r=t.reload();assert.equal(r.modal,'resume');assert.equal(r.pick(r.game.solution[3]),false);assert.deepEqual(r.game.serialize(),before);r.action('resume');assert.deepEqual(r.game.serialize(),before);assert.equal(r.tool('undo'),true);assert.equal(r.game.reserve.length,3);r.tool('shuffle');const snapshot=r.game.serialize(),g=Game.restore(snapshot);g.tools.shuffle=1;r.game.tools.shuffle=1;g.use('shuffle');r.game.use('shuffle');assert.deepEqual(g.serialize(),r.game.serialize());});
test('TEST-DAILY-04 old run continues across midnight and abandonment uses actual date',()=>{const t=setup(),c=t.c;c.pick(c.game.solution[0]);c.tool('undo');t.setTime('2026-09-30T16:01:00Z');win(c);c.action('next');assert.equal(c.challengeDate,'2026-09-30');assert.equal(c.game.tools.undo,0);assert.deepEqual(c.game.tiles,new Game(2,seedFor('2026-09-30',2)).tiles);const r=t.reload();r.saved.adLedger.days['2026-10-01']=1;r.action('abandonResume');assert.equal(r.challengeDate,'2026-10-01');assert.equal(r.game.config.level,1);assert.equal(r.saved.adLedger.days['2026-10-01'],1);assert.equal(r.game.tools.undo,1);});
test('TEST-DAILY-05 full tray rescue and terminal loss persist, history survives',()=>{const t=setup({level:20}),c=t.c;full(c.game);c.game.tools.remove=1;c.settle();assert.equal(c.modal,'lost');assert.equal(c.tool('shuffle'),false);assert.equal(c.tool('remove'),true);assert.equal(c.game.tray.length,4);full(c.game);c.game.tools.undo=0;c.game.tools.remove=0;c.settle();assert.equal(c.saved.run.status,'ended');assert.equal(t.reload().modal,'ended');const h=clone(c.saved.history);c.action('retry');assert.equal(c.game.config.level,1);assert.deepEqual(c.saved.history,h);});
test('TEST-DAILY-06 level 30 has no 31 or loop; completion survives reload',()=>{const t=setup({level:30}),c=t.c;win(c);assert.equal(c.saved.run.status,'completed');c.action('next');assert.equal(c.game.config.level,30);assert.equal(t.reload().modal,'won');c.action('retry');assert.equal(c.game.config.level,1);assert.equal(c.saved.history[0].result,'completed');assert.ok(c.saved.completed.includes(30));});
test('TEST-DAILY-07 native match in seventh slot precedes loss and undo restores triple',()=>{const g=new Game(20);g.tiles.forEach((t,i)=>{t.zone=i<6?'tray':'board';t.z=0;t.x=i*2;});g.tray=[0,1,2,3,4,5];[0,0,1,1,2,2,0].forEach((type,i)=>g.tiles[i].type=type);g.pick(6);assert.equal(g.status,'playing');assert.deepEqual(g.tray,[2,3,4,5]);g.use('undo');assert.deepEqual(g.tray,[0,1,2,3,4,5]);assert.equal(g.tools.undo,0);});
test('TEST-DAILY-08 default ads never call SDK or grant even with injected provider',async()=>{let calls=0;const ads=new AdGateway({enabled:true,provider:{rewarded:()=>{calls++;return {completed:true};}}});ads.enabled=true;assert.equal((await ads.reward('undo',()=>calls++)).status,'unavailable');assert.equal((await ads.revive(()=>calls++)).status,'unavailable');assert.equal(calls,0);});
test('TEST-DAILY-09 future revival returns oldest three visibly, reserve unchanged, conserves cards',()=>{const {c}=setup({level:20});full(c.game);[7,8,9].forEach((id,i)=>Object.assign(c.game.tiles[id],{zone:'reserve',reserveOrder:i}));const before=clone(c.game.reserve),tray=c.game.tray.slice(),types=c.game.tiles.map(t=>t.type);assert.equal(applyReward(c.saved,c.game,{id:'r1',date:'2026-10-01',runId:c.saved.run.id,level:20,kind:'revive'}),true);assert.deepEqual(c.game.tray,tray.slice(3));assert.deepEqual(c.game.reserve,before);assert.deepEqual(c.game.tiles.map(t=>t.type),types);assert.equal(c.game.remaining,c.game.tiles.length);for(const id of tray.slice(0,3)){assert.equal(c.game.canPick(id),true);assert.equal(available(c.game.tiles,c.game.tiles[id]),true);for(const other of c.game.tiles.filter(t=>t.zone==='board'&&t.id!==id))assert.ok(Math.abs(other.x-c.game.tiles[id].x)>=.94||Math.abs(other.y-c.game.tiles[id].y)>=.94);}assert.equal(c.game.history,null);});
test('TEST-DAILY-10 future shared actual-date quota is idempotent across runs and midnight',()=>{const {c}=setup({level:20});const receipt=(id,date,kind)=>({id,date,kind,runId:c.saved.run.id,level:c.game.config.level});for(const [i,key] of ['undo','shuffle','remove'].entries()){c.game.tools[key]=0;assert.equal(applyReward(c.saved,c.game,receipt('id'+i,'2026-10-01',key)),true);}c.game.tools.undo=0;assert.equal(applyReward(c.saved,c.game,receipt('id0','2026-10-02','undo')),false);assert.equal(applyReward(c.saved,c.game,receipt('id4','2026-10-01','undo')),false);assert.equal(applyReward(c.saved,c.game,receipt('id5','2026-10-02','undo')),true);c.start(1);c.game.tools.undo=0;assert.equal(applyReward(c.saved,c.game,receipt('id6','2026-10-01','undo')),false);assert.equal(c.saved.adLedger.days['2026-10-02'],1);});
test('TEST-DAILY-11 invalid/stale future reward leaves both game and quota unchanged',()=>{const {c}=setup();for(const receipt of [null,{id:'x',date:'2026-10-01',runId:'stale',kind:'undo',level:1},{id:'x',date:'2026-10-01',runId:c.saved.run.id,kind:'revive',level:1}]){const before=JSON.stringify([c.saved,c.game.serialize()]);assert.equal(applyReward(c.saved,c.game,receipt),false);assert.equal(JSON.stringify([c.saved,c.game.serialize()]),before);}});
test('TEST-DAILY-12 unknown config keeps saved data untouched, old progress migrates history only',()=>{const t=setup({level:20});const data=t.p.readDaily();data.run.configVersion='future-v2';t.p.saveDaily(data);assert.equal(t.reload().modal,'storage');assert.deepEqual(t.p.readDaily(),data);const store={'dimsum.production.progress.v1':{level:20,completed:[1,2,3]}};const {c}=setup({store,version:'release'});assert.equal(c.game.config.level,1);assert.deepEqual(c.saved.completed,[1,2,3]);assert.equal(store['dimsum.production.progress.v1'].level,20);});
