const {test}=require('node:test');const assert=require('node:assert/strict');
const {Game,LEVELS,available}=require('../prototypes/snack-tiles/game.js');const {AdGateway}=require('../prototypes/snack-tiles/ads.js');
test('all 30 configurations and 600 seeded boards have a legal no-tool solution',()=>{for(const c of LEVELS)for(let seed=1;seed<=20;seed++){const g=new Game(c.level,c.seed+seed);assert.equal(g.tiles.length,c.count);assert.equal(new Set(g.tiles.map(t=>t.type)).size,c.types);const counts={};g.tiles.forEach(t=>counts[t.type]=(counts[t.type]||0)+1);Object.values(counts).forEach(n=>assert.equal(n%3,0));for(const id of g.solution){assert.equal(g.pick(id),true,`level ${c.level}, seed ${seed}, tile ${id}`);assert.ok(g.tray.length<7);}assert.equal(g.status,'won');assert.equal(g.remaining,0);}});
test('covered tiles cannot be picked',()=>{const g=new Game(30);const t=g.tiles.find(t=>!available(g.tiles,t));assert.ok(t);assert.equal(g.pick(t.id),false);assert.equal(g.moves,0);});
function setup(types){const g=new Game(1);g.tiles=types.map((type,id)=>({id,type,x:id,y:0,z:0,zone:'board'}));return g;}
test('a match in the seventh slot resolves before loss, and undo restores consumed triple',()=>{const g=setup([0,1,2,3,4,0,0]);for(let i=0;i<7;i++)g.pick(i);assert.equal(g.status,'playing');assert.equal(g.tray.length,4);assert.equal(g.use('undo'),true);assert.equal(g.tray.length,6);assert.equal(g.tiles[6].zone,'board');assert.equal(g.tiles[0].zone,'tray');assert.equal(g.tools.undo,0);});
test('full nonmatching tray loses; remove preserves cards and recovers play',()=>{const g=setup([0,1,2,3,4,5,6,0,0]);for(let i=0;i<7;i++)g.pick(i);assert.equal(g.status,'lost');assert.equal(g.pick(7),false);assert.equal(g.use('remove'),true);assert.equal(g.status,'playing');assert.equal(g.reserve.length,3);assert.equal(g.tray.length,4);assert.equal(g.remaining,9);assert.equal(g.use('remove'),false);assert.equal(g.pick(0),true);assert.equal(g.reserve.length,2);});
test('win includes reserve and all tools have strict eligibility',()=>{const g=setup([0,1,2]);assert.equal(g.use('undo'),false);assert.equal(g.use('remove'),false);g.tiles.forEach(t=>t.zone='reserve');g.settle();assert.equal(g.status,'playing');assert.equal(g.remaining,3);g.tiles.forEach(t=>t.zone='gone');g.settle();assert.equal(g.status,'won');assert.equal(g.use('shuffle'),false);});
test('shuffle preserves board counts, tray, reserve and tool limit',()=>{const g=new Game(20);g.solution.slice(0,4).forEach(id=>g.pick(id));const before=g.tiles.filter(t=>t.zone==='board').map(t=>t.type).sort();const tray=[...g.tray];assert.ok(g.use('shuffle'));assert.deepEqual(g.tiles.filter(t=>t.zone==='board').map(t=>t.type).sort(),before);assert.deepEqual(g.tray,tray);assert.equal(g.use('shuffle'),false);assert.equal(g.history,null);});
test('ad gateway is off by default; grants only confirmed complete views; handles failure',async()=>{let count=0,calls=0;const provider={rewarded:async()=>{calls++;return{completed:true};}};assert.equal((await new AdGateway({provider}).reward('undo',()=>count++)).status,'unavailable');assert.equal(calls,0);const a=new AdGateway({enabled:true,provider});assert.equal((await a.reward('undo',()=>count++)).status,'granted');assert.equal(count,1);provider.rewarded=async()=>({completed:false});assert.equal((await a.reward('undo',()=>count++)).status,'cancelled');provider.rewarded=async()=>{throw Error('network');};assert.equal((await a.reward('undo',()=>count++)).status,'failed');assert.equal(count,1);assert.equal(a.busy,false);});
test('concurrent reward requests cannot duplicate grant',async()=>{let resolve,count=0;const a=new AdGateway({enabled:true,provider:{rewarded:()=>new Promise(r=>resolve=r)}});const p=a.reward('undo',()=>count++);assert.equal((await a.reward('undo',()=>count++)).status,'unavailable');resolve({completed:true});await p;assert.equal(count,1);});
