'use strict';
const {Game,LEVELS,FOODS,normalizeLevel}=SnackGame;
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search);
const TEST_MODE=['localhost','127.0.0.1',''].includes(location.hostname)&&params.get('mode')!=='production';
const STORAGE_KEY=TEST_MODE?'snack-progress-test-v2':'snack-progress-prod-v2',ads=new SnackAds.AdGateway();
const FOOD_NAMES=FOODS.map((n,i)=>i===8?'蛋散':n);
// Figma sprite crops: x, y, width, height, image width/height/left/top percentages.
const FOOD_ART=[[7,6,38,35,368.26,417.65,-16.77,-11.11],[6,5,40,38,354.47,405.71,-239.19,-9.84],[7,7,40,35,342.62,405.71,-119.22,-106.98],[6.15,5.1,40,38,376.15,407.01,-133.33,-9.55],[6,7,40,33,336.99,414.94,-223.56,-114.94],[8,6,36,37,407.28,412.26,-21.85,-111.61],[6,7,40,33,355.12,143.48,-10.07,-21.21],[6,7,40,33,355.12,143.48,-127.57,-21.21],[6,7,40,33,355.12,143.48,-245.07,-21.21]];
function art(type,blocked=false,scale){const a=FOOD_ART[type],style=scale===undefined?'':` style="transform:scale(${scale})"`;const food=a?`<span class="food-window" style="left:${a[0]}px;top:${a[1]}px;width:${a[2]}px;height:${a[3]}px"><img alt="" src="assets/${type>=6?'food-extra':'food-sheet'}.png" style="width:${a[4]}%;height:${a[5]}%;left:${a[6]}%;top:${a[7]}%"></span>`:`<span class="food-fallback">${FOOD_NAMES[type]}</span>`;return `<span class="card-art" aria-hidden="true"${style}><span class="card-base"></span><span class="card-face"></span>${food}${blocked?'<span class="card-mask"></span>':''}</span>`;}
let saved={level:1,completed:[]};try{const raw=localStorage.getItem(STORAGE_KEY)||(TEST_MODE?localStorage.getItem('snack-progress-v1'):null),d=JSON.parse(raw||'{}');if(d&&typeof d==='object'&&!Array.isArray(d)){saved.completed=Array.isArray(d.completed)?[...new Set(d.completed.filter(n=>Number.isInteger(n)&&n>=1&&n<=LEVELS.length))]:[];saved.level=normalizeLevel(d.level);}}catch{}
function unlocked(){let n=1;while(n<LEVELS.length&&saved.completed.includes(n))n++;return n;}
if(!TEST_MODE)saved.level=Math.min(saved.level,unlocked());
let game,feedbackTimer;
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(saved));}catch{}}
function feedback(text){$('feedback').textContent=text;$('feedback').classList.toggle('visible',!!text);clearTimeout(feedbackTimer);if(text)feedbackTimer=setTimeout(()=>$('feedback').classList.remove('visible'),2400);}
function start(level){if($('result').open)$('result').close();const target=normalizeLevel(level);game=new Game(TEST_MODE?target:Math.min(target,unlocked()));saved.level=game.config.level;persist();feedback('');render();}
function pick(id){if(!game.pick(id))return;feedback(game.lastMatch?'三张相同，已消除':game.tray.length>=5?'暂存槽快满了，留意可配对的小吃':'');if(game.status==='won'){if(!saved.completed.includes(game.config.level))saved.completed.push(game.config.level);saved.level=Math.min(game.config.level+1,LEVELS.length);persist();}render();}
function fit(){const w=Math.min(document.documentElement.clientWidth||window.innerWidth,480),h=window.innerHeight,scale=Math.min(w/402,h/640),logicalH=h/scale,root=document.documentElement;root.style.setProperty('--view-width',`${402*scale}px`);root.style.setProperty('--view-height',`${h}px`);root.style.setProperty('--scene-scale',scale);root.style.setProperty('--scene-height',`${logicalH}px`);root.style.setProperty('--safe-top',`${logicalH<720?64:88}px`);root.style.setProperty('--safe-bottom',`${logicalH<720?24:34}px`);if(game)render();}
function layout(){const board=$('board'),width=board.clientWidth,height=board.clientHeight;if(game.config.level===20&&window.SnackDesign20){const d=SnackDesign20,s=Math.min(1,(height-18)/d.height,(width-24)/d.width),left=(width-d.width*s)/2,top=(height-d.height*s)/2;return d.tiles.map(t=>({id:t.id,x:left+t.x*s,y:top+t.y*s,w:t.w*s,h:t.h*s}));}const ts=game.tiles,minX=Math.min(...ts.map(t=>t.x)),minY=Math.min(...ts.map(t=>t.y)),sx=Math.max(...ts.map(t=>t.x))+.94-minX,sy=Math.max(...ts.map(t=>t.y))+.94*54/52-minY,unit=Math.min(55.4,(width-28)/sx,(height-24)/sy);return ts.map(t=>({id:t.id,x:(width-sx*unit)/2+(t.x-minX)*unit,y:(height-sy*unit)/2+(t.y-minY)*unit,w:unit*.94,h:unit*.94*54/52}));}
function render(){const c=game.config,eliminated=c.count-game.remaining;$('levelTitle').textContent=`第 ${String(c.level).padStart(2,'0')} 关`;$('progressLabel').textContent=`已消除 ${eliminated} / ${c.count}`;$('progress').style.width=`${eliminated/c.count*100}%`;$('progressTrack').setAttribute('aria-valuemax',c.count);$('progressTrack').setAttribute('aria-valuenow',eliminated);$('used').textContent=game.tray.length;
 const board=$('board');board.replaceChildren();for(const p of layout()){const t=game.tiles[p.id];if(t.zone!=='board')continue;const b=document.createElement('button');b.className='tile';b.dataset.tile=t.id;b.style.cssText=`left:${p.x}px;top:${p.y}px;width:${p.w}px;height:${p.h}px;z-index:${t.z+1}`;b.disabled=!game.canPick(t.id);b.setAttribute('aria-label',`${FOOD_NAMES[t.type]}，第${t.z+1}层${b.disabled?'，被遮挡':'，可选'}`);b.innerHTML=art(t.type,b.disabled,p.w/52);b.onclick=()=>pick(t.id);board.append(b);}
 $('tray').classList.toggle('warning',game.tray.length>=5);$('tray').innerHTML=Array.from({length:7},(_,i)=>{const id=game.tray[i],filled=id!==undefined;return `<div class="slot ${filled?'filled':''}" aria-label="第${i+1}格${filled?'，'+FOOD_NAMES[game.tiles[id].type]:'，空'}">${filled?art(game.tiles[id].type):''}</div>`;}).join('');
 $('reserve').replaceChildren();for(let i=0;i<3;i++){const t=game.reserve[i],el=document.createElement(t?'button':'span');el.className='reserve-slot';el.setAttribute('aria-label',t?`${FOOD_NAMES[t.type]}，点回暂存槽`:`临时区第${i+1}格，空`);if(t){el.innerHTML=art(t.type);el.disabled=!game.canPick(t.id);el.onclick=()=>pick(t.id);}$('reserve').append(el);}
 document.querySelectorAll('[data-tool]').forEach(b=>{const k=b.dataset.tool;b.disabled=!game.canTool(k);b.querySelector('small').textContent=`剩余${game.tools[k]}次`;b.setAttribute('aria-label',`${{undo:'撤回',shuffle:'洗牌',remove:'移出3张'}[k]}，剩余${game.tools[k]}次`);});renderResult();}
function renderResult(){const result=$('result');if(game.status==='playing'){if(result.open)result.close();return;}const win=game.status==='won',last=game.config.level===LEVELS.length;$('resultTitle').textContent=win?'这一关，全部消除！':'暂存槽已满';const recovery=!win&&(game.canTool('undo')||game.canTool('remove'));$('resultText').textContent=win?(last?'全部关卡已完成！可以重玩本关。':`用了 ${game.moves} 次选牌，下一笼小吃等着你。`):recovery?'使用剩余道具继续，或重新挑战本关。':'本局已无可用的恢复道具，重新挑战一次吧。';const actions=[];if(win){actions.push([last?'重玩本关':'下一关',async()=>{const button=$('resultActions').querySelector('button');button.disabled=true;try{await ads.settlement();}finally{start(last?game.config.level:game.config.level+1);}}]);if(last&&TEST_MODE)actions.push(['选择关卡',()=>{result.close();showLevels();}]);}else{for(const[k,label]of[['undo','撤回继续'],['remove','移出3张继续']])if(game.canTool(k))actions.push([label,()=>use(k)]);actions.push(['重试本关',()=>start(game.config.level)]);}$('resultActions').replaceChildren();actions.forEach(([label,fn],i)=>{const b=document.createElement('button');b.textContent=label;if(i===0)b.className='primary';b.onclick=fn;$('resultActions').append(b);});if(!result.open)result.showModal();}
function use(key){if(game.use(key)){feedback({undo:'已还原上一步选牌',shuffle:'棋盘图案已重新打乱',remove:'已移出3张，点临时区的小吃可放回暂存槽'}[key]);render();}}
function modal(title,html){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();}
function showLevels(){if(!TEST_MODE)return;modal('选择测试关卡',`<div class="levelgrid">${LEVELS.map(c=>`<button data-level="${c.level}" ${c.level===game.config.level?'class="primary"':''}>${String(c.level).padStart(2,'0')}<small>${saved.completed.includes(c.level)?'已完成':c.count+'张'}</small></button>`).join('')}</div><p class="legend">仅测试预览开放全部关卡，测试进度独立保存。</p>`);document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{$('dialog').close();start(b.dataset.level);});}
$('scene').classList.toggle('production',!TEST_MODE);$('levels').tabIndex=TEST_MODE?0:-1;$('levels').setAttribute('aria-hidden',String(!TEST_MODE));$('levels').onclick=showLevels;$('restart').onclick=()=>{modal('重新开始本关？','<p>本局进度将重置，道具次数恢复。</p><p><button id="confirmRestart" class="primary">重新开始</button></p>');$('confirmRestart').onclick=()=>{$('dialog').close();start(game.config.level);};};
$('rules').onclick=()=>modal('玩法与道具','<ol><li>点击未被上层遮挡的小吃，放入七格暂存槽。</li><li>凑齐三张相同小吃立即消除；未消除且满七格时，本局暂停。</li><li>撤回：还原最近一次选牌，包括刚消除的牌。</li><li>洗牌：打乱棋盘图案，不改变暂存槽和临时区。</li><li>移出：将最早入槽的三张移至临时区，需要点回继续消除。</li><li>每种道具每关可用一次；清空全部小吃即可通关。</li></ol><p>无计时。刷新会重新开始本关，已完成关卡进度保存在当前设备。</p>');$('closeDialog').onclick=()=>$('dialog').close();$('result').addEventListener('cancel',e=>e.preventDefault());document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>use(b.dataset.tool));window.addEventListener('resize',fit);fit();start(TEST_MODE&&params.has('level')?normalizeLevel(params.get('level')):saved.level);

