// Browser integration verification. Start an isolated Chrome CDP session on 9237 first.
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
const targets=await(await fetch('http://127.0.0.1:9237/json')).json();const ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let serial=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(pending.has(m.id)){const {resolve,reject}=pending.get(m.id);pending.delete(m.id);m.error?reject(Error(JSON.stringify(m.error))):resolve(m.result);}};
const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
const run=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
const wait=ms=>new Promise(r=>setTimeout(r,ms));const navigate=async url=>{await send('Page.navigate',{url});await wait(450);for(let n=0;n<60;n++){if(await run("document.readyState==='complete'&&typeof game!=='undefined'&&[...document.images].every(i=>i.complete&&i.naturalWidth>0)"))return;await wait(100);}throw Error('Page/assets not ready');};
const screenshot=async name=>{await wait(200);const r=await send('Page.captureScreenshot',{format:'png'});fs.writeFileSync('artifacts/main-ui-v1/'+name+'.png',Buffer.from(r.data,'base64'));};
const click=async selector=>{const pos=await run(`(()=>{const n=document.querySelector(${JSON.stringify(selector)});if(!n)throw Error('Missing click target');const r=n.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()`);await send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...pos});await send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...pos});};
await send('Page.enable');await send('Runtime.enable');
const layouts=[];for(const [width,height] of [[402,734],[375,667],[390,844],[430,932],[320,568]]){
 await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:true});await navigate('http://127.0.0.1:4173/?level=20');
 const r=await run(`(()=>{const b=$('board').getBoundingClientRect(),s=document.querySelector('.storage').getBoundingClientRect(),t=document.querySelector('.tools').getBoundingClientRect();return{width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth,tiles:document.querySelectorAll('.tile').length,available:document.querySelectorAll('.tile:not(:disabled)').length,slots:document.querySelectorAll('#tray>.slot').length,reserve:$('reserve').children.length,toolsBottom:t.bottom,storageTop:s.top,boardBottom:b.bottom,assets:[...document.images].every(i=>i.naturalWidth>0),tileBounds:[...document.querySelectorAll('.tile')].every(e=>{const r=e.getBoundingClientRect();return r.left>=b.left-1&&r.right<=b.right+1&&r.top>=b.top-1&&r.bottom<=b.bottom+1;})};})()`);
 console.log(r);assert.equal(r.overflow,false);assert.equal(r.tiles,84);assert.equal(r.available,9);assert.equal(r.slots,7);assert.equal(r.reserve,3);assert.ok(r.toolsBottom<=height);assert.ok(r.boardBottom<=r.storageTop+.1);assert.ok(r.assets&&r.tileBounds);layouts.push(r);await screenshot(`level20-${width}x${height}`);
}
await send('Emulation.setDeviceMetricsOverride',{width:402,height:734,deviceScaleFactor:1,mobile:true});await navigate('http://127.0.0.1:4173/?level=20');
await click('.tile:not(:disabled)');assert.equal(await run('game.moves'),1);assert.equal(await run('game.tray.length'),1);await click('[data-tool=undo]');assert.equal(await run('game.moves'),0);assert.equal(await run('game.tools.undo'),0);
await run('start(20)');const counts=await run('JSON.stringify(game.tiles.map(t=>t.type).sort())');await click('[data-tool=shuffle]');assert.equal(await run('game.tools.shuffle'),0);assert.equal(await run('JSON.stringify(game.tiles.map(t=>t.type).sort())'),counts);
await run('start(20)');await run('for(const id of game.solution.slice(0,3))document.querySelector(`[data-tile="${id}"]`).click()');assert.equal(await run('game.tray.length'),3);const first=await run('JSON.stringify(game.tray)');await click('[data-tool=remove]');assert.equal(await run('JSON.stringify(game.reserve.map(t=>t.id))'),first);await click('#reserve button');assert.equal(await run('game.reserve.length'),2);await click('[data-tool=undo]');assert.equal(await run('game.reserve.length'),3);await screenshot('reserve-and-undo');
await click('#rules');assert.ok(await run("$('dialog').open"));await click('#closeDialog');const before=await run('JSON.stringify(game.snapshot())');await click('#restart');await click('#closeDialog');assert.equal(await run('JSON.stringify(game.snapshot())'),before);await click('#restart');await click('#confirmRestart');assert.equal(await run('game.moves'),0);
await click('#levels');await click('[data-level="1"]');await run('for(const id of game.solution.slice())document.querySelector(`[data-tile="${id}"]`).click()');assert.equal(await run('game.status'),'won');assert.ok(await run("$('result').open"));await screenshot('win');await click('#resultActions button');assert.equal(await run('game.config.level'),2);
// Reproducible actual wrong-order play: no injected loss state.
await run(`(()=>{for(let attempt=0;attempt<40;attempt++){start(20);let seed=attempt+1;while(game.status==='playing'){const open=game.tiles.filter(t=>game.canPick(t.id));seed=(Math.imul(seed,1664525)+1013904223)>>>0;const t=open[seed%open.length];document.querySelector('[data-tile="'+t.id+'"]').click();}if(game.status==='lost')return;}throw Error('No losing path found');})()`);
assert.ok(await run("$('result').open"));await screenshot('full-tray');await click('#resultActions button');assert.equal(await run('game.status'),'playing');assert.equal(await run("$('result').open"),false);
const testSave=await run("localStorage.getItem('snack-progress-test-v2')");await run("localStorage.removeItem('snack-progress-prod-v2')");await navigate('http://127.0.0.1:4173/?mode=production&level=20');assert.equal(await run('game.config.level'),1);assert.equal(await run("getComputedStyle($('levels')).visibility"),'hidden');await run('showLevels()');assert.equal(await run("$('dialog').open"),false);await run('game.solution.slice().forEach(id=>pick(id))');await click('#resultActions button');assert.equal(await run('game.config.level'),2);await navigate('http://127.0.0.1:4173/?mode=production');assert.equal(await run('game.config.level'),2);assert.equal(await run("localStorage.getItem('snack-progress-test-v2')"),testSave);await screenshot('production');
await navigate('http://127.0.0.1:4173/?level=30');assert.equal(await run('game.config.level'),30);assert.ok(await run("document.querySelectorAll('.food-fallback').length>0"));await navigate('http://127.0.0.1:4173/?level=20');
assert.equal(errors.length,0,JSON.stringify(errors));const report={date:new Date().toISOString(),method:'Chrome headless CDP with pointer input and DOM actions; isolated profile',layouts,interaction:'passed: pick, undo, shuffle, reserve order/return, restart cancel/confirm, rules, level picker, win/next, natural loss/recovery, production gate/save isolation/reload',consoleExceptions:errors,realDevice:'not tested',missingArt:'levels 21-30: fried egg, noodles, soy milk retain text placeholders'};fs.writeFileSync('artifacts/main-ui-v1/browser-check.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));ws.close();
})().catch(e=>{console.error(e);process.exit(1)});

