const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),base=path.join(root,'prototypes/snack-tiles');
const {Game,LEVELS}=require(path.join(base,'game.js'));const {AdGateway}=require(path.join(base,'ads.js'));
const results=[];
async function scenario(id,title,rule,setup,steps,fn){try{await fn();results.push({id,title,rule,setup,steps,status:'通过'});}catch(e){results.push({id,title,rule,setup,steps,status:'失败',error:e.message});}}
function app(initial,blocked=false){const values=new Map(initial===undefined?[]:[['snack-progress-test-v2',initial]]),els=new Map();class El{constructor(){this.children=[];this.clientWidth=370;this.clientHeight=269;this.attributes={};this.style={setProperty(){}};this.dataset={};this.classList={toggle(){}};this.textContent='';}set innerHTML(v){this.html=v;this.children=[];}get innerHTML(){return this.html;}append(e){this.children.push(e);}replaceChildren(...items){this.children=items;}addEventListener(){}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}querySelector(k){return this.small??=new El();}showModal(){this.open=true;}close(){this.open=false;}}
const get=id=>{if(!els.has(id))els.set(id,new El());return els.get(id);};const buttons=['undo','shuffle','remove'].map(k=>{const e=new El();e.dataset.tool=k;return e;});const ctx=vm.createContext({console,URLSearchParams,location:{search:'',hostname:'127.0.0.1'},setTimeout:()=>0,clearTimeout(){},document:{documentElement:{style:{setProperty(){}}},getElementById:get,createElement:()=>new El(),querySelectorAll:q=>q==='[data-tool]'?buttons:[]},window:{addEventListener(){},innerWidth:402,innerHeight:734},localStorage:{getItem:k=>{if(blocked)throw Error('denied');return values.get(k)??null;},setItem:(k,v)=>{if(blocked)throw Error('denied');values.set(k,v);}}});for(const f of ['game.js','ads.js','app.js'])vm.runInContext(fs.readFileSync(path.join(base,f),'utf8'),ctx,{filename:f});return{run:s=>vm.runInContext(s,ctx),get,values};}
if(require.main===module)(async()=>{
await scenario('QA-001','实际默认30关可解','RULE-001/002/003','默认种子；普通玩家；全部30关','按合法通关见证逐张选牌→每步合法→清空获胜',()=>{for(const c of LEVELS){const g=new Game(c.level);for(const id of g.solution)assert.equal(g.pick(id),true);assert.equal(g.status,'won');}});
await scenario('QA-002','同一张牌重复提交','RULE-002','第1关；普通玩家','连续两次选择同一张→第二次拒绝→不重复增加步数',()=>{const g=new Game(1),id=g.solution[0];g.pick(id);const before=JSON.stringify(g.snapshot());assert.equal(g.pick(id),false);assert.equal(JSON.stringify(g.snapshot()),before);});
await scenario('QA-003','非法牌编号无副作用','RULE-001','第10关；普通玩家','输入-1、999、null、undefined→拒绝且状态不变',()=>{const g=new Game(10),s=JSON.stringify(g.snapshot());for(const id of [-1,999,null,undefined])assert.equal(g.pick(id),false);assert.equal(JSON.stringify(g.snapshot()),s);});
await scenario('QA-004','移出按先入槽顺序而非牌编号排列','RULE-006','隔离6种可选牌；普通玩家；先点ID 5、2、4','移出3张→临时区按原先入槽顺序5、2、4展示',()=>{const g=new Game(1);g.tiles=Array.from({length:6},(_,id)=>({id,type:id,x:id,y:0,z:0,zone:'board'}));[5,2,4].forEach(i=>g.pick(i));assert.ok(g.use('remove'));assert.deepEqual(g.reserve.map(t=>t.id),[5,2,4]);});
await scenario('QA-005','撤回临时区选牌','RULE-004/006','隔离可选牌；普通玩家','移出→点回一张→撤回→临时区、槽和步数恢复',()=>{const g=new Game(1);g.tiles=Array.from({length:6},(_,id)=>({id,type:id,x:id,y:0,z:0,zone:'board'}));[0,1,2].forEach(i=>g.pick(i));g.use('remove');const before=g.snapshot();g.pick(0);assert.ok(g.use('undo'));assert.deepEqual(g.snapshot(),before);assert.equal(g.tools.undo,0);});
await scenario('QA-006','固定重开与道具恢复','RULE-008','第1、10、20、30关；普通玩家','开局保存牌局→选牌并用道具→重建本关→牌局与初始次数一致',()=>{for(const n of [1,10,20,30]){const g=new Game(n),snapshot=g.snapshot();g.pick(g.solution[0]);g.use('undo');const fresh=new Game(n);assert.deepEqual(fresh.snapshot(),snapshot);assert.deepEqual(fresh.tools,{undo:1,shuffle:1,remove:1});}});
await scenario('QA-007','300局混合操作状态一致','RULE-001—007','30关各10局；确定性操作序列；普通玩家','混合选牌/撤回/洗牌/移出→每步核对牌归属、槽容量、胜负、次数',()=>{let seed=872;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};for(let n=1;n<=30;n++)for(let k=0;k<10;k++){const g=new Game(n);for(let step=0;step<150;step++){const actions=g.tiles.filter(t=>g.canPick(t.id)).map(t=>()=>g.pick(t.id));for(const key of ['undo','shuffle','remove'])if(g.canTool(key))actions.push(()=>g.use(key));if(!actions.length)break;actions[Math.floor(rand()*actions.length)]();assert.ok(g.tray.length<=7);assert.equal(new Set(g.tray).size,g.tray.length);assert.deepEqual(g.tiles.filter(t=>t.zone==='tray').map(t=>t.id).sort((a,b)=>a-b),[...g.tray].sort((a,b)=>a-b));assert.ok(g.reserve.length<=3);assert.ok(Object.values(g.tools).every(x=>x===0||x===1));assert.equal(g.status,g.remaining===0?'won':g.tray.length===7?'lost':'playing');}}});
await scenario('QA-008','页面控制完成与下一关','REQ-001/RULE-003','DOM替身；第1关；普通玩家','调用选牌处理器完成1关→显示结算→触发下一关按钮→进入2关',async()=>{const a=app();a.run('game.solution.slice().forEach(id=>pick(id))');assert.equal(a.run('game.status'),'won');assert.equal(a.get('result').open,true);await a.get('resultActions').children[0].onclick();assert.equal(a.run('game.config.level'),2);});
await scenario('QA-009','最终关返回选关与进度去重','RULE-008','DOM替身；第30关；普通玩家','完成30关→返回选关→重玩再赢→完成记录仅一项30',async()=>{const a=app();a.run('start(30);game.solution.slice().forEach(id=>pick(id))');await a.get('resultActions').children[1].onclick();assert.equal(a.get('dialog').open,true);assert.equal(a.get('dialogTitle').textContent,'选择测试关卡');a.run('start(30);game.solution.slice().forEach(id=>pick(id))');assert.deepEqual(JSON.parse(a.values.get('snack-progress-test-v2')).completed,[30]);});
await scenario('QA-010','重新加载只恢复关卡与完成记录','RULE-008','DOM替身；已完成第1关；正在第10关','结束1关→进入10关选牌→以相同存档重新初始化→10关新局且1关仍完成',()=>{const a=app();a.run('game.solution.slice().forEach(id=>pick(id));start(10);pick(game.solution[0])');const b=app(a.values.get('snack-progress-test-v2'));assert.equal(b.run('game.config.level'),10);assert.equal(b.run('game.moves'),0);assert.equal(b.run('saved.completed.includes(1)'),true);});
await scenario('QA-011','存储被禁止或JSON损坏','RULE-008','DOM替身；存储异常；普通玩家','拒绝存储访问或加载非法JSON→仍能进入第1关并选牌',()=>{for(const a of [app(undefined,true),app('{broken')]){assert.equal(a.run('game.config.level'),1);a.run('pick(game.solution[0])');assert.equal(a.run('game.moves'),1);}});
await scenario('QA-012','存档关卡为小数时安全恢复','RULE-008','DOM替身；存档为{"level":1.5,"completed":[]}；普通玩家','重新打开→校验关卡→回退有效整数关卡且页面可玩',()=>{const a=app('{"level":1.5,"completed":[]}');assert.equal(Number.isInteger(a.run('game.config.level')),true);});
await scenario('QA-013','重开取消不丢失局面','RULE-008','DOM替身；第10关已点一张；普通玩家','打开重开确认→关闭弹窗→局面保留→再次打开并确认→重置',()=>{const a=app();a.run('start(10);pick(game.solution[0]);document.getElementById("restart").onclick()');const before=a.run('JSON.stringify(game.snapshot())');a.get('closeDialog').onclick();assert.equal(a.run('JSON.stringify(game.snapshot())'),before);a.run('document.getElementById("restart").onclick()');a.get('confirmRestart').onclick();assert.equal(a.run('game.moves'),0);assert.equal(a.get('dialog').open,false);});
await scenario('QA-014','未启用广告时结算不调用供应商','REQ-004','虚拟广告供应商；默认关闭','触发结算及奖励请求→零供应商调用、零奖励',async()=>{let called=0;const ads=new AdGateway({provider:{interstitial:()=>called++,rewarded:()=>called++}});assert.equal(await ads.settlement(),false);assert.equal((await ads.reward('undo',()=>called++)).status,'unavailable');assert.equal(called,0);});
const out=path.join(root,process.env.SNACK_TEST_ARTIFACT_DIR||'.cache/tester-latest');fs.mkdirSync(out,{recursive:true});
const hashes={};for(const f of ['game.js','ads.js','app.js','index.html','style.css'])hashes[f]=crypto.createHash('sha256').update(fs.readFileSync(path.join(base,f))).digest('hex');
fs.writeFileSync(path.join(out,'qa-results.json'),JSON.stringify({date:new Date().toISOString(),version:process.env.SNACK_TEST_VERSION||'working-copy',node:process.version,method:'Node core + isolated vm/DOM substitute, NOT real browser',hashes,results},null,2));
console.log(results.map(r=>r.status+' '+r.id+' '+r.title+(r.error?' — '+r.error:'')).join('\n'));
console.log('TOTAL '+results.length+'; FAILED '+results.filter(r=>r.status==='失败').length);
process.exitCode=results.some(r=>r.status==='失败')?1:0;
})();
module.exports={app};

